version: 1
formatters:
  default:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: default
    filename: logs/logfile.log
loggers:
  issf_scraper:
    level: DEBUG
    handlers: [file]
    propagate: no
root:
  level: INFO
  handlers: [file]
